### ISSUE TITLE
React-redux project

### ISSUE THREAD

**Issue by cherelemma** [Microverse-Fullstack-Program/space-travelers-hub#25]
Team Member: 1
[Project Link](https://github.com/Microverse-Fullstack-Program/space-travelers-hub/projects/1)

**Comment by prolajumokeoni** [comment]
Hi @cherelemma could you please add a screenshot from student success to allow you work solo?

**Comment by cherelemma** [comment]
> Hi @cherelemma could you please add a screenshot from student success to allow you to work solo?

![image](https://user-images.githubusercontent.com/73167960/220036058-e294d770-f3f0-4a4b-8582-eb6627e80a8a.png)

![image](https://user-images.githubusercontent.com/73167960/220036178-ada8d343-2aeb-4744-a591-8d4232535149.png)

**Comment by prolajumokeoni** [comment]
Hi @cherelemma 

Your board setup is complete! 
Congratulations! 🎉 
## Highlights
 - Good setup   💯  

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

- Well done setting up your Github project 👏🏿,  As you are currently working solo you are required to complete the activities for Rockets and My Profile page for the project, You can consider adding mission or/and dragon as optional if you wish. All the best ✌️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by prolajumokeoni** [comment]
> > Hi @cherelemma could you please add a screenshot from student success to allow you to work solo?
> 
> ![image](https://user-images.githubusercontent.com/73167960/220036058-e294d770-f3f0-4a4b-8582-eb6627e80a8a.png)
> 
> ![image](https://user-images.githubusercontent.com/73167960/220036178-ada8d343-2aeb-4744-a591-8d4232535149.png)

thanks for adding it, all the best with the project 🤗
